[package]
name = "finddup"
version = "0.1.0"
authors = ["devdufutur <devdufutur@domain.tld>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
blake2 = "0.9.1"
indicatif = "0.15.0"