name: Rust

on:
  tags:
    - *

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/release/finddup(.exe)?
    - name: Build
      run: cargo build --release --verbose
#    - name: Run tests
#      run: cargo test --verbose
